use new stages names to silence pre-commit warning
scop/pre-commit-shfmt pull request #31
Opened 2024-10-09 10:03 UTC by JulienGrv

This fixes following warning:

```
[INFO] Initializing environment for https://github.com/scop/pre-commit-shfmt.
[WARNING] repo `https://github.com/scop/pre-commit-shfmt` uses deprecated stage names (commit, merge-commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/scop/pre-commit-shfmt` will fix this.  if it does not -- consider reporting an issue to that repo.
[INFO] Installing environment for https://github.com/scop/pre-commit-shfmt.
```

2024-10-14 06:19 UTC, scop commented
I believe (but have not verified) that doing this would mean that the hooks would no longer work with pre-commit < 4. If so, I'm inclined to not make this change yet.

2024-10-14 11:46 UTC, JulienGrv commented
Hi @scop , AFAIK the warnings were introduced with [version 4.0](https://github.com/pre-commit/pre-commit/releases/tag/v4.0.0) but the new names are there since [version 3.2](https://github.com/pre-commit/pre-commit/releases/tag/v3.2.0). Anyway, I don't mind leaving this PR opened until you think the time is right

2024-10-22 20:45 UTC, scop commented
Thanks for the info, looks like the "new" names are available since 3.2.0 indeed, which I think is old enough for this change.

2024-10-22 20:47 UTC, scop requested changes

2024-10-22 20:47 UTC, scop commented on .pre-commit-hooks.yaml
> +  stages: [pre-commit, pre-merge-commit, pre-push, manual]
To err on the side of caution, let's add a minimum pre-commit version to all these changes, like in https://github.com/scop/pre-commit-perlcritic/commit/d2b81b4977a45d6cbc651bdfb5a713832a1d98f2

2024-11-13 21:25 UTC, scop approved these changes
Thanks!

2024-11-13 21:26 UTC, merged

2024-11-25 11:04 UTC, lucasfijen commented
Hey! Nice to see you already merged a fix for the deprecation warnings.
Is there any chance on a new releasing for this hook so we can get rid of these warnings?:)

2024-12-01 09:06 UTC, scop commented
`v3.10.0-2` tagged now.